### ISSUE TITLE
Use Templateflow to download necessary templates

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsirecon_build#4]
At minimum, QSIRecon, requires the res-1 MNI152NLin2009cAsym and MNIInfant (cohort-2) T1w templates, along with the associated brain masks.

I think this would replace https://github.com/PennLINC/qsirecon_build/blob/7b466befcaf1ebac2a9a14080993566affe70c0c/docker/scripts/get_templates.sh.

Related to https://github.com/PennLINC/qsirecon/pull/49.

**Comment by mattcieslak** [comment]
I think get_templates.sh has actually not been useful at all since we switched to synthstrip/synthseg. those were only used for ants brain extraction in the past
